const buildingsData = [
    {value: "AAPB", label: "Anthro/Art Practice Building"},
    {value: "BAMU", label: "Berkeley Art Museum"},
    {value: "BARK", label: "Barker Hall"},
    {value: "BECH", label: "Bechtel Engineering Center, Sibley Auditorium"},
    {value: "BIRG", label: "Birge Hall"},
    {value: "BWWB", label: "Berkeley Way West Building"},
    {value: "CORY", label: "Cory Hall"},
    {value: "DAVS", label: "Davis Hall"},
    {value: "DONN", label: "Donner Laboratory"},
    {value: "DWIN", label: "Dwinelle Hall"},
    {value: "WHLR", label: "Wheeler Hall"},
    {value: "WURS", label: "Wurster Hall"},
    {value: "SOCS", label: "Social Sciences Building"},
    {value: "STAN", label: "Stanley Hall"},
    {value: "SUTD", label: "Sutardja Dai Hall"},
    {value: "TANH", label: "Tan Hall"},
    {value: "VLSB", label: "Valley Life Sciences Building"},
    {value: "WEIL", label: "Joan and Sanford I. Weill Hall"},
    {value: "PHYS", label: "Physics Building"},
    {value: "PMTL", label: "Pimentel Hall"},
    {value: "LATI", label: "Latimer Hall"},
    {value: "LEWS", label: "Lewis Hall"},
    {value: "MCCN", label: "McCone Hall"},
    {value: "MOFF", label: "Moffitt Undergraduate Library"},
    {value: "MORG", label: "Morgan Hall"},
    {value: "MULF", label: "Mulford Hall"},
    {value: "NGAT", label: "North Gate Hall"},
    {value: "EVAN", label: "Evans Hall"},
    {value: "GIAN", label: "Giannini Hall"},
    {value: "GPBB", label: "Genetics & Plant Biology Building"},
    {value: "GSPP", label: "Goldman School of Public Policy"},
    {value: "HAAS", label: "Haas Faculty Wing"},
    {value: "HAVI", label: "Haviland Hall"},
    {value: "HFAX", label: "Hearst Field Annex"},
    {value: "HGYM", label: "Hearst Memorial Gymnasium"},
    {value: "HILD", label: "Hildebrand Hall"},
    {value: "HMMB", label: "Hearst Memorial Mining Building"},
    {value: "ETCH", label: "Etcheverry Hall"}
  ];
export default buildingsData;